### ISSUE TITLE
Include 'messageTemplate' in log messages

### ISSUE THREAD

**Issue by mrmartan** [mattwcole/gelf-extensions-logging#35]
Would it be possible to include 'messageTemplate' in log messages?
I.e.:
```csharp
logger.LogError("This is a TEST message. Result is {result}", result);
```
would produce:
```
message_template | This is a TEST message from. Result is {result}
message | This is a TEST message from. Result is bar
result | bar
```

**Comment by mattwcole** [comment]
This should be quite simple to add to [`GelfLogger`](https://github.com/mattwcole/gelf-extensions-logging/blob/dev/src/Gelf.Extensions.Logging/GelfLogger.cs#L114). Alternatively you could decorate the logger, although this is a fair amount of code to get the decorator registered (assuming you're using .NET Core DI). I've created an example [here](https://gist.github.com/mattwcole/895f5a4b6ad3abace77ff23ab826d135) that shows how to do this. It will also add the level string you were after in #34.

**Comment by mrmartan** [comment]
That's true. I could do that. Although adding it to the library would be much cleaner and (I imagine) easier.

**Comment by mrmartan** [comment]
@mattwcole Aren't you just removing the original message, i.e. the thing I am after? Why is that? https://github.com/mattwcole/gelf-extensions-logging/blob/dev/src/Gelf.Extensions.Logging/GelfLogger.cs#L117

**Comment by mrmartan** [comment]
Additionally, I am not sure it is correct to remove the last item like that. There might be something I am missing, but it seems the last item does not have to be `OriginalFormat`.

![image](https://user-images.githubusercontent.com/2376580/62294801-126b4b80-b46c-11e9-92e6-ca0b3a3d5e3a.png)

**Comment by mattwcole** [comment]
The last item is always `OriginalFormat` as long as `logValues` is an instance of `FormattedLogValues` (see [here](https://github.com/aspnet/Extensions/blob/master/src/Logging/Logging.Abstractions/src/FormattedLogValues.cs#L67)). This code changed recently in #33 which is only in the pre-release version of the library for .NET Core 3.0, so perhaps you have found a bug! Switch to the master branch to see the current stable release code.

As for why `OriginalFormat` was removed in the first place - probably just because the key doesn't match the format of the others. Should be a small change to add back in.

**Comment by mrmartan** [comment]
As you can see from the screenshot. That's taken using ASP.NET Core 2.2.6 and is a log message produced by MVC itself. So should I rather use `FormattedLogValues`? I can see you are no longer using it the dev branch.

**Comment by mrmartan** [comment]
Right now I have ended up with:
```csharp
if (state is IEnumerable<KeyValuePair<string, object>> logValues)
{
    var originalFormat = logValues.LastOrDefault(pair => pair.Key == "{OriginalFormat}");
    if (originalFormat.Key != default)
    { 
        additionalFields["message_template"] = originalFormat.Value;
    }
}
```

**Comment by mattwcole** [comment]
That looks like it will work. We stopped using `FormattedLogValues` because that type has become internal in .NET Core 3.0.

A simple fix for the library would just be to stop trying to excluding `OriginalFormat`, and just add all the fields in [`GelfLogger.GetStateAdditionalFields`](https://github.com/mattwcole/gelf-extensions-logging/blob/dev/src/Gelf.Extensions.Logging/GelfLogger.cs#L114). I will make this change unless you feel like creating a PR. If people care enough about inconsistent key name formats we can open a separate issue to control the format with options e.g.

```csharp
new GelfLoggerOptions
{
    ...
    AdditionalFieldsKeyMap = new Dictionary<string, string>
    {
        ["OriginalFormat"] = "message_template",
        ["SomeFrameworkField"] = "some_framework_field"
    }
    ...
}
```

**Comment by mattwcole** [comment]
I have just made [a change](https://github.com/mattwcole/gelf-extensions-logging/commit/adf9214300fa375484c5e1e8f2715bcfec210a2b) to add the option to include message templates and pushed to NuGet as a [pre-release](https://www.nuget.org/packages/Gelf.Extensions.Logging/1.5.2-pre2). You can enable it in appsettings.json. Let me know if you have any problems.

**Comment by mrmartan** [comment]
I feel like caring about inconsistent names is inconsequential. If you were to use `log scopes` you would have the key names inconsistent anyway as those follow C# conventions.
