### ISSUE TITLE
String valued timestamps creates error messages

### ISSUE THREAD

**Issue by joshuanario** [mattwcole/gelf-extensions-logging#5]
Issue: The log messages from the gelf client has double quotes around the `timestamp` value, which deserializes into a string and causes the graylog server to send error messages that looks like the following: `2017-11-03T19:43:16.768Z WARN [GelfCodec] GELF message <3cb9eaf2-c0cf-11e7-bfec-42010af0000e> (received from <10.180.2.6:41948>) has invalid "timestamp": 1509738196.720 (type: STRING)`.  Below is a sample gelf message from the gelf client (`Gelf.Extensions.Logging v1.1.0`) extracted from a UDP packet capture using wireshark:
```
{
  "version": "1.1",
  "host": "blueprint2-backend",
  "short_message": "Pepe1S3mFSiVyM1V",
  "timestamp": "1510345173.212",
  "level": 2,
  "_logger": "app.api.controllers.TestController",
  "_machine_name": "500d5cb21c8f"
}
```

Dev Notes:

The graylog server (`v2.3.2`) throws an `IllegalArgumentException` when `isNumber` asserts false.  See code:
```
        final JsonNode timestampNode = jsonNode.path("timestamp");
        if (timestampNode.isValueNode() && !timestampNode.isNumber()) {
            throw new IllegalArgumentException(prefix + "has invalid \"timestamp\": " + timestampNode.asText());
        }
```
https://github.com/Graylog2/graylog2-server/blob/4ffda524aac8054712b811f8e78c232be8b24a0d/graylog2-server/src/main/java/org/graylog2/inputs/codecs/GelfCodec.java#L262

Recommendation: Consider changing the DTO's `Timestamp` property from `string` to `double` in order to JSON serialize the `timestamp` value as a numeric data in compliance to the gelf spec (http://docs.graylog.org/en/2.2/pages/gelf.html#gelf-payload-specification).
https://github.com/mattwcole/gelf-extensions-logging/blob/7628544a0da1a603b86875133c75c7cfa13d8794/src/Gelf.Extensions.Logging/GelfMessage.cs#L19

**Comment by mattwcole** [comment]
Thanks for the detailed error description, much appreciated!

From what I can tell, Graylog only complains about this since v2.3.x, but it is still certainly a bug. I've released a [quick fix](https://github.com/mattwcole/gelf-extensions-logging/commit/f71119e38eb6ac34927d3add397e23cc238b0eb3) as [v1.2.1-pre1](https://www.nuget.org/packages/Gelf.Extensions.Logging/1.2.1-pre1) that should be available on nuget.org as soon as it is indexed.

I'll update the tests to use Graylog 2.3.2 and make sure the change is covered before releasing a stable version.

**Comment by mattwcole** [comment]
v1.2.1 is now released with the fix.
