### ISSUE TITLE
Option to enable/disable Semantic Logging

### ISSUE THREAD

**Issue by vas7n** [mattwcole/gelf-extensions-logging#66]
It would be nice to add an option to enable/disable Structured/Semantic Logging.

For example, so that the parameters are not created if I use `_logger.LogInformation("Order {order_id} took {order_time} seconds to process", orderId, orderTime);`.

![image](https://user-images.githubusercontent.com/14210834/170662349-c6dfb046-47dc-460e-99ad-7abf7b33c5ef.png)

**Comment by mattwcole** [comment]
Hi, what would the reason be to disable this behavior? [Log message templates](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0#log-message-template) are used specifically for the purpose of enabling structured logging. Are you aware of other providers that support disabling structured logs?

**Comment by vas7n** [comment]
Hi! The reason is simple. My administrators forbid creating any other parameters (tags).

**Comment by mattwcole** [comment]
Forbidding additional fields seems like an odd decision since this is one of the main reasons for using a tool like Graylog. You can use string interpolation to bypass the structured logging but in general you shouldn't do this because you lose information, and can't easily query your logs.

```csharp
_logger.LogInformation($"Order {orderId} took {orderTime} seconds");
```

**Comment by vas7n** [comment]
> ```cs
> _logger.LogInformation($"Order {orderId} took {orderTime} seconds");
> ```

In this case, I will get a warning: "[CA2254: The template must be a static expression](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2254)"

I fully trust your expert opinion. And if you really think this is a bad idea, you can close the Issue.

**Comment by mattwcole** [comment]
Sorry for the delay getting back to you, the warning is there because you are losing the structured data, but that is what you are trying to achieve, so you can ignore it (more info [here](https://stackoverflow.com/a/65938575/4832982)).

You can [disable the warning](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/suppress-warnings), or try to convince your admins of the [value of structured logs](https://softwareengineering.stackexchange.com/questions/312197/benefits-of-structured-logging-vs-basic-logging) :)
